data_path: data_original
data_gen_path: data
training_set_path: /training_set
test_set_path: /test_set
case_path: /cas.jpg
test_folder: /real_test_set
epochs: 5
optimizer: adam
rescale: 255
shear_range: 0.3
zoom_range: 0.4
horizontal_flip: False
target_size: 124
batch_size: 16
loss: categorical_crossentropy