batch_size: 16
case_path: /cas.jpg
data_gen_path: data
data_path: data_original
data_version: 3
epochs: 10
experiment_name: experiment_1
horizontal_flip: true
loss: categorical_crossentropy
optimizer: adam
rescale: 255
shear_range: 0.3
target_size: 124
test_folder: /real_test_set
test_set_path: /test_set
training_set_path: /training_set
zoom_range: 0.3
